spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    com.simple.trading.robot: trace

simple-trading-robot:
  token:
  sandbox-token:
  strategies:
    - enabled: true
      name: strategy1
      strategy-type: simple_strategy
      instrument: inst_name
      account:
        id: 123
        max-sum: 10000.3
        max-percent: 44
    - enabled: true
      name: strategy2
      strategy-type: simple_strategy
      instrument: inst_name
      account:
        id: 123
        max-sum: 10000.22
        max-percent: 46.5
    - enabled: true
      name: strategy3
      strategy-type: simple_strategy
      instrument: inst_name
      account:
        id: 123
        max-sum: 10000.22
        max-percent: 46.5
        sandbox: true
    - enabled: false
      name: strategy4
      strategy-type: another_strategy
      instrument: inst_name
      account:
        id: 123
        max-sum: 10000.22
        max-percent: 46.5