spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true

logging:
  level:
    com.simple.trading.robot: trace

simple-trading-robot:
  tinkoff-api:
    token: ${TINKOFF_TOKEN}
    sandbox-token: ${TINKOFF_SANDBOX_TOKEN}
  threads:
    always-active: 2
    max-size: 10
    seconds-to-live: 10
  strategies:
    - enabled: true
      name: strategy1
      strategy-type: simple_strategy
      instrument:
        ticker: RIH5
        type: future
      account:
        api: tinkoff_api
        id: 123
        max-sum: 10000.3
        max-percent: 44
    - enabled: true
      name: strategy2
      strategy-type: simple_strategy
      instrument:
        ticker: IMOEXF
        type: future
      account:
        api: tinkoff_api
        id: 123
        max-sum: 10000.22
        max-percent: 46.5
    - enabled: true
      name: strategy3
      strategy-type: simple_strategy
      instrument:
        ticker: SBERF
        type: future
      account:
        api: tinkoff_api
        id: 123
        max-sum: 10000.22
        max-percent: 46.5
        is-sandbox: true
    - enabled: false
      name: strategy4
      strategy-type: another_strategy
      instrument:
        ticker: inst_name
        type: bond
      account:
        api: tinkoff_api
        id: 123
        max-sum: 10000.22
        max-percent: 46.5